name: Build
on: [push, pull_request, workflow_dispath]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the current repo files and
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
        node-version: '12.x'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # Install node requirements and then install jupyter
      - run: npm install
      - run: npm install -g configurable-http-proxy
      - run: python -m pip install -U jupyterhub jupyterlab

      # Install the extension and check that it installed correctly
      - run: pip install .
      - run: pip list | grep jupyterhub-entrypoint